services:
  postgres:
    image: postgres:16
    container_name: hackaton-auth-postgres
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hackaton-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hackaton-auth-backend
    ports:
      - "8082:8082"
    networks:
      - hackaton-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  hackaton-network: