spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: hackaton-auth
  threads:
    virtual:
      enabled: true
  flyway:
    enabled: false
  security:
    user:
      name: admin
      password: admin
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# Configuração do Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true

logging:
  level:
    tech.challenge: debug
    org.apache.kafka: info
    org.springframework.kafka: debug

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20
  forward-headers-strategy: native

jwt:
  secret: SEFDS0FUT05fMjAyNV9TRU5IQV9HUk9VUF8xN19GSUFQWAo=
  expiration:
    ms: 86400000