spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hackaton
    username: hackaton
    password: hackaton
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:29092