apiVersion: v1
kind: ConfigMap
metadata:
  name: hackaton-auth-config
data:
  DATABASE: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_HOST: "hackaton-auth-db.cs34oe66a9rt.us-east-1.rds.amazonaws.com"
  EMAIL_USERNAME: "fiapxgrupo17hackaton@gmail.com"
  EMAIL_PASSWORD: "fuzv lolj ymlt xtjb"
  SERVER_PORT: "8080"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  JWT_EXPIRATION: "86400000"

---
apiVersion: v1
kind: Secret
metadata:
  name: hackaton-auth-secret
type: Opaque
data:
  DATABASE_USER: "aGFja2F0b24="  # Base64 encoded "hackaton"
  DATABASE_PASSWORD: "VGVzdGUxMjM="  # Base64 encoded "Teste123"
  JWT_SECRET: "bXktc3VwZXItc2VjdXJlLWp3dC1rZXktdGhhdC1pcy12ZXJ5LWxvbmctYW5kLXNlY3VyZS1mb3ItcHJvZHVjdGlvbi1hbmQtbXVzdC1iZS1hdC1sZWFzdC0yNTYtYml0cy1mb3ItaG1hYy1zaGEtYWxnb3JpdGhtcw=="
